app/app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('', include('payment.urls')),

]

app/payment/urls.py
from django.urls import include, path
from .views import CheckoutView, ProductView, StatusView, OrdersList, OrdersDelete, CheckStock
from django.views.generic.base import RedirectView
from rest_framework import routers

app_name = 'payment'

router = routers.DefaultRouter()
router.register('products', ProductView, 'Products')

urlpatterns = [
    path('', include(router.urls)),
    path('checkout', CheckoutView.as_view(), name='checkout'),
    path('status', StatusView.as_view(), name='status'),
    path('stock', CheckStock.as_view(), name='stock'),
    path('orders', OrdersList.as_view(), name='orders'),
    path('orders/<int:pk>/delete', OrdersDelete.as_view(), name='delete'),
    # path('redirect', RedirectView.as_view(
    #     url='http://localhost:3000/orders'), name='redirect'),
    path('redirect', RedirectView.as_view(
        url='https://e-shopp-react.netlify.app/orders'), name='redirect'),
]

app/payment/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from accounts.models import User
# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=30)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    img_url = models.CharField(max_length=300)
    stock = models.IntegerField()

    def get_name(self):
        return self.name

    def get_stock(self):
        return self.stock

    def __str__(self):
        return self.name


class Transaction(models.Model):
    user = models.ForeignKey(
        User, related_name="orders", on_delete=models.CASCADE)
    txnid = models.CharField(max_length=40, unique=True)
    product = models.ManyToManyField(Product)
    amount = models.DecimalField(max_digits=7, decimal_places=2)
    email = models.EmailField(max_length=40)
    date = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)

    # def get_username(self):
    #     return self.user.get_name()

    # def get_product_name(self):
    #     return self.product.get_name()

    def __str__(self):
        return self.txnid

app/payment/forms.py
from django.forms import ModelForm
from .models import Transaction


class TransactionForm(ModelForm):

    class Meta:
        model = Transaction
        fields = ['txnid', 'amount', 'product', 'email']


class ExtraFields(TransactionForm):
    product = Transaction.get_product_name()
    name = Transaction.get_username()

app/payment/views.py
from operator import truediv
from accounts.models import User
# from django.views.decorators.csrf import csrf_exempt
import random
import string
import hashlib
from django.shortcuts import redirect, render
from .models import Transaction, Product
from rest_framework.viewsets import ModelViewSet
from rest_framework.views import APIView
from rest_framework.generics import CreateAPIView, RetrieveUpdateAPIView, ListAPIView, DestroyAPIView
from rest_framework import permissions, status
from .serializers import ProductSerializer, TransactionSerializer
from rest_framework.response import Response

# sha512 vd2Y1X|k8WnSppfWj5dO5|10.00|iPhone|PayU User|test@gmail.com|||||||||||Brg97QyF
# test card 5123-4567-8901-2346 4012-0010-3714-1112 123 123456


class ProductView(ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class CheckStock(APIView):
    def post(self, request):
        print(request)
        ids = request.data['ids']
        stock = True
        for id in ids:
            product = Product.objects.get(id=id)
            if product.stock == 0:
                stock = False
        return Response(stock)


class CheckoutView(CreateAPIView):
    permission_class = [permissions.IsAuthenticated]
    serializer_class = TransactionSerializer

    def create(self, request, *args, **kwargs):
        key = 'gtKFFx'
        salt = 'wia56q6O'
        print(request.data)
        name = request.user.name
        email = request.user.email

        product_ids = request.data['product_ids']
        amount = request.data['amount']
        names = request.data['names']
        txnid = ''.join(random.choices(
            string.ascii_uppercase + string.digits, k=24))

        try:
            serializer = self.get_serializer(data={
                'txnid': txnid,
                'product': product_ids,
                'user': request.user.id,
                'email': email,
                'amount': amount

            })
            serializer.is_valid(raise_exception=True)
            self.perform_create(serializer)

            strg = key + '|' + txnid + '|' + str(amount) + '|' + \
                names + '|' + name + '|' + email + '|||||||||||' + salt
            hash = hashlib.sha512(strg.encode()).hexdigest()
            print()
            context = {
                'id': serializer.data['id'],
                'key': key,
                'salt': salt,
                'txnid': txnid,
                'amount': str(amount),
                'product': names,
                'name': name,
                'email': email,
                # 'surl': 'http://localhost:8000/status',
                # 'furl': 'http://localhost:8000/status',
                'surl': 'https://e-shopp-django.herokuapp.com/status',
                'furl': 'https://e-shopp-django.herokuapp.com/status',
                'hash': hash

            }
        except Exception as e:
            print(e)
            raise

        headers = self.get_success_headers(serializer.data)
        return Response(context, status=status.HTTP_201_CREATED, headers=headers)


class OrdersList(ListAPIView):
    serializer_class = TransactionSerializer
    permission_class = [permissions.IsAuthenticated]

    def get_queryset(self):
        user = self.request.user
        return user.orders.all().order_by('-date')

    # def perform_update(self, serializer):
    #     serializer.save(status=True)


class OrdersDelete(DestroyAPIView):
    queryset = Transaction.objects.all()
    serializer_class = TransactionSerializer
    permission_class = [permissions.IsAuthenticated]


class StatusView(APIView):

    def post(self, request, *args, **kwargs):
        status = request.POST.get('status')
        txnid = request.POST.get('txnid')

        t = Transaction.objects.get(txnid=txnid)
        if status == 'success':
            t.status = True
            t.save()
            products = t.product.all()
            print(products)
            for prod in products:
                if prod.stock > 0:
                    prod.stock -= 1
                    print(prod.stock)
                    prod.save()

            print("completed for:" + t.user.name)
        return redirect('payment:redirect')

# @login_required(login_url='/login/')
# @csrf_exempt
# def status(request):
#     if request.method == "POST":
#         data = dict(request.POST)
#         status = request.POST.get('status')
#         txnid = request.POST.get('txnid')

#         t = Transaction.objects.get(txnid=txnid)
#         if status == 'success':
#             t.status = True
#             t.save()
#             print("completed for:" + t.user.name)

#         context = {
#             'txnid': txnid,
#             'status': status,
#             'product': t.product.name,

#         }

#         return render(request, 'status.html', context=context)


# class OrdersList(LoginRequiredMixin, ListView):
#     login_url = '/login/'

#     model = Transaction
#     template_name = "orders.html"
#     ordering = ['-date']

    # Array
    # (
    #     [mihpayid] => 13297721729
    #     [mode] => CASH
    #     [status] => success
    #     [unmappedstatus] => captured
    #     [key] => vd2Y1X
    #     [txnid] => k8WnSppfWj5dO7
    #     [amount] => 10.00
    #     [discount] => 0.00
    #     [net_amount_debit] => 10
    #     [addedon] => 2021-06-18 01:14:54
    #     [productinfo] => iPhone
    #     [firstname] => nishant
    #     [lastname] =>
    #     [address1] =>
    #     [address2] =>
    #     [city] =>
    #     [state] =>
    #     [country] =>
    #     [zipcode] =>
    #     [email] => test@gmail.com
    #     [phone] =>
    #     [udf1] =>
    #     [udf2] =>
    #     [udf3] =>
    #     [udf4] =>
    #     [udf5] =>
    #     [udf6] =>
    #     [udf7] =>
    #     [udf8] =>
    #     [udf9] =>
    #     [udf10] =>
    #     [hash] => e478ad7837422810ff482efca9d8f402fccf4342ad38cb03b23d3311884a1b5dccfecdf135f24a29e815672d2681a5df38d5362b18989d94d8b0ff41d01fb37f
    #     [field1] => 2021-06-18 01:15:16.0
    #     [field2] => 20210618111212800110168941914234127
    #     [field3] => 13297721729
    #     [field4] =>
    #     [field5] =>
    #     [field6] =>
    #     [field7] =>
    #     [field8] =>
    #     [field9] => Txn Success
    #     [payment_source] => payu
    #     [meCode] => {"payee_id":"PayUGo96421738082175","clientId":"C11"}
    #     [PG_TYPE] => CASH-PG
    #     [bank_ref_num] => 20210618111212800110168941914234127
    #     [bankcode] => PAYTM
    #     [error] => E000
    #     [error_Message] => No Error
    # )

app/payment/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Payment</title>
</head>

<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">E Shopping</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link " aria-current="page" href={% url 'payment:checkout' %}>Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href={% url 'payment:orders' %}>Orders</a>
        </li>

        {% if request.user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link "  tabindex="-1" aria-disabled="true" href={% url 'accounts:logout' %}>Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href={% url 'accounts:register' %}>Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link " href={% url 'accounts:login' %} tabindex="-1" aria-disabled="true">Login</a>
        </li>
        {% endif %}
        
        
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid p-3 mt-3 " >
  {% block body %}

    {% endblock %}
</div>
    
</body>

{% block script %}
{% endblock %}
</html>

app/payment/templates/checkout.html
{% extends "base.html" %}
{% block body %}

<div class="container">
  <div class="row row-cols-3">
    {% for product in products %}
    <div class="col">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
          <img src={{product.img_url}}
            style=" max-height:200px;display: block; margin-left: auto; margin-right: auto;width: auto;"
            class="card-img-top">
          <h5 class="card-title">{{product.name}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">₹ {{product.price}}</h6>
          <form method="post">
            {% csrf_token %}
            <input type="hidden" name="pk" value="{{product.pk}}">
            <input class="btn btn-outline-success" type="submit" name="submit" value="Buy">
          </form>
        </div>
      </div>
    </div>
    {% endfor %}


  </div>
</div>



{% endblock %}

app/payment/templates/orders.html
{% extends "base.html" %}
{% block body %}
<div class="container border p-3" style="max-width:876px">
    <table class="table">
    <thead>
        <tr>
        <th scope="col">Product</th>
        <th scope="col">Amount</th>
        <th scope="col">Status</th>
        </tr>
    </thead>
    <tbody>
        {% for order in object_list %}
        
        <tr>
        <td>{{order.product.name}}</td>
        <td>{{order.product.price}}</td>
        <td>
            {% if order.status %}
                <span class="badge bg-success">Complete</span>
            {% else %}
                <span class="badge bg-warning text-dark">Failed</span>
            {% endif %}
        </td>
        </tr>
        
        {% endfor %}
    
    </tbody>
    </table>
</div>

{% endblock %}

app/payment/templates/redirect.html
{% extends "base.html" %}
{% block body %}
<div class="container m-3 p-3 border">
    <h3 class="display-6">Payment</h3>
    <hr>
    <section>
        <span><b>Total Amount:</b> ₹{{amount}}</span>
    </section>
    <section>
        <h4>Pay using </h4>
        <div class="form-check p-3 mb-3">
            <input class="form-check-input" type="radio" name="gridRadios" id="gridRadios2" value="option2">
            <label class="form-check-label" for="gridRadios2">
                <img height="40%" width="40%" src="https://seeklogo.com/images/P/payu-logo-C104D0EC9F-seeklogo.com.png"
                    alt="PayU">
            </label>
        </div>

    </section>

    <form method="post" action="https://test.payu.in/_payment" name="form">
        {% csrf_token %}
        <input type="hidden" name="key" value="{{key}}">
        <input type="hidden" name="txnid" value="{{txnid}}">
        <input type="hidden" name="amount" value="{{amount}}">
        <input type="hidden" name="productinfo" value="{{product}}">
        <input type="hidden" name="firstname" value="{{name}}">
        <input type="hidden" name="email" value="{{email}}">
        <input type="hidden" name="surl" value="{{surl}}">
        <input type="hidden" name="hash" value="{{hash}}">
    </form>
    <button class="btn btn-primary mb-3" onclick="check()" id="button">Submit</button>

</div>
{% endblock %}
{% block script %}
<script>
    function check() {
        radio = document.getElementById("gridRadios2");
        console.log(radio.checked);

        if (radio.checked) {
            document.form.submit();
        }
    }
</script>

{% endblock %}

app/payment/templates/status.html
{% extends "base.html" %}
{% block body %}
    <div class="container border w-50">
        
        {% if status == "success" %}
            <h3>Your Order has been placed</h3><hr>
            <p>Payment Approved</p>
        {% else %}
            <h3>Order Failed!</h3><hr>
            <p>Payment Failed</p>
        {% endif %} 
        <p>Product: {{product}}</p>
        
        <p>Order id: {{txnid}}</p>
    </div>

{% endblock %}